import socket
import rsa
print("[1] Creating TCP socket for RSA client...")
client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
print("[2] Connecting to RSA server at localhost:12346 ...")
client_socket.connect(('localhost', 12346))
print("[✔] Connected to RSA Server.\n")
print("[3] Waiting to receive public key from server...")
public_key_data = client_socket.recv(1024).decode()
print(f"[4] Public key received: {public_key_data}")
n, e = map(int, public_key_data.split(','))
server_pubkey = rsa.PublicKey(n, e)
print("[✔] Public key parsed successfully.\n")
message = input("Enter message to send securely: ")
print(f"[5] Encrypting message using server's public key...")
cipher_data = rsa.encrypt(message.encode(), server_pubkey)
print(f"[✔] Encryption complete. Ciphertext length: {len(cipher_data)}
bytes\n")
print("[6] Sending encrypted message to server...")
client_socket.send(cipher_data)
print("[✔] Ciphertext sent successfully!\n")
print("[7] Closing connection with server...")
client_socket.close()
print("[✔] RSA Client finished successfully.")
